def genBoard():
    # Constants
    WHITE = '0'
    BLACK = '1'
    EMPTY = '000'
    PAWN = '001'
    KNIGHT = '010'
    BISHOP = '011'
    ROOK = '100'
    QUEEN = '101'
    KING = '110'
    
    # Construct board by cols
    """
    # Position 1: initial board state, Perft(1) = 20
    COL8 = [BLACK, ROOK,   BLACK, PAWN, BLACK, EMPTY, BLACK, EMPTY, WHITE, EMPTY, WHITE, EMPTY, WHITE, PAWN, WHITE, ROOK]
    COL7 = [BLACK, KNIGHT, BLACK, PAWN, BLACK, EMPTY, BLACK, EMPTY, WHITE, EMPTY, WHITE, EMPTY, WHITE, PAWN, WHITE, KNIGHT]
    COL6 = [BLACK, BISHOP, BLACK, PAWN, BLACK, EMPTY, BLACK, EMPTY, WHITE, EMPTY, WHITE, EMPTY, WHITE, PAWN, WHITE, BISHOP]
    COL5 = [BLACK, KING,   BLACK, PAWN, BLACK, EMPTY, BLACK, EMPTY, WHITE, EMPTY, WHITE, EMPTY, WHITE, PAWN, WHITE, KING]
    COL4 = [BLACK, QUEEN,  BLACK, PAWN, BLACK, EMPTY, BLACK, EMPTY, WHITE, EMPTY, WHITE, EMPTY, WHITE, PAWN, WHITE, QUEEN]
    COL3 = [BLACK, BISHOP, BLACK, PAWN, BLACK, EMPTY, BLACK, EMPTY, WHITE, EMPTY, WHITE, EMPTY, WHITE, PAWN, WHITE, BISHOP]    
    COL2 = [BLACK, KNIGHT, BLACK, PAWN, BLACK, EMPTY, BLACK, EMPTY, WHITE, EMPTY, WHITE, EMPTY, WHITE, PAWN, WHITE, KNIGHT]
    COL1 = [BLACK, ROOK,   BLACK, PAWN, BLACK, EMPTY, BLACK, EMPTY, WHITE, EMPTY, WHITE, EMPTY, WHITE, PAWN, WHITE, ROOK]
    
    """
    # Position 2: Perft(1) = 48, 8 capt, 2 castl (46 pseudo, no castl)
    COL8 = [BLACK, ROOK, BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY,   WHITE, EMPTY, BLACK, PAWN, WHITE, PAWN, WHITE, ROOK];
    COL7 = [BLACK, EMPTY, BLACK, BISHOP, BLACK, PAWN, BLACK, EMPTY,  BLACK, EMPTY, WHITE, EMPTY, WHITE, PAWN, WHITE, EMPTY];
    COL6 = [BLACK, EMPTY, BLACK, PAWN, BLACK, KNIGHT, BLACK, EMPTY,  WHITE, EMPTY, WHITE, QUEEN, WHITE, PAWN, WHITE, EMPTY];
    COL5 = [BLACK, KING, BLACK, QUEEN, BLACK, PAWN, WHITE, KNIGHT,   WHITE, PAWN, WHITE, EMPTY, WHITE, BISHOP, WHITE, KING];
    COL4 = [BLACK, EMPTY, BLACK, PAWN, BLACK, EMPTY, WHITE, PAWN,    WHITE, EMPTY, WHITE, EMPTY, WHITE, BISHOP, WHITE, EMPTY];
    COL3 = [BLACK, EMPTY, BLACK, PAWN, BLACK, EMPTY, BLACK, EMPTY,   WHITE, EMPTY, WHITE, KNIGHT, WHITE, PAWN, WHITE, EMPTY];
    COL2 = [BLACK, EMPTY, BLACK, EMPTY, BLACK, KNIGHT, BLACK, EMPTY, BLACK, PAWN, WHITE, EMPTY, WHITE, PAWN, WHITE, EMPTY];
    COL1 = [BLACK, ROOK, BLACK, PAWN, BLACK, BISHOP, BLACK, EMPTY,   WHITE, EMPTY, WHITE, EMPTY, WHITE, PAWN, WHITE, ROOK];
    
    """
    # Position 3: Perft(1) = 14, 1 capt, 2 checks (16 pseudo)
    COL8 = [BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY, BLACK, ROOK, BLACK, KING, WHITE, EMPTY, WHITE, EMPTY, WHITE, EMPTY]
    COL7 = [BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY, WHITE, PAWN, BLACK, EMPTY]
    COL6 = [BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY, BLACK, PAWN, BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY]
    COL5 = [BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY, WHITE, PAWN, BLACK, EMPTY]
    COL4 = [BLACK, EMPTY, BLACK, EMPTY, BLACK, PAWN, BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY]
    COL3 = [BLACK, EMPTY, BLACK, PAWN, BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY]
    COL2 = [BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY, WHITE, PAWN, WHITE, ROOK, BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY]
    COL1 = [BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY, WHITE, KING, BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY, BLACK, EMPTY]
    """
    """
    # Position 4: Perft(1) = 6
    COL8 = [BLACK, ROOK, BLACK, PAWN, WHITE, KNIGHT, WHITE, EMPTY, WHITE, EMPTY, WHITE, EMPTY, WHITE, PAWN, WHITE, EMPTY]
    COL7 = [WHITE, EMPTY, BLACK, PAWN, BLACK, BISHOP, WHITE, EMPTY, WHITE, EMPTY, WHITE, EMPTY, WHITE, PAWN, WHITE, KING]
    COL6 = [WHITE, EMPTY, BLACK, PAWN, BLACK, KNIGHT, WHITE, EMPTY, WHITE, EMPTY, WHITE, KNIGHT, WHITE, EMPTY, WHITE, ROOK]
    COL5 = [BLACK, KING, WHITE, EMPTY, WHITE, EMPTY, WHITE, EMPTY, WHITE, PAWN, WHITE, EMPTY, WHITE, EMPTY, WHITE, EMPTY]
    COL4 = [WHITE, EMPTY, BLACK, PAWN, WHITE, EMPTY, WHITE, EMPTY, WHITE, EMPTY, WHITE, EMPTY, WHITE, PAWN, WHITE, QUEEN]
    COL3 = [WHITE, EMPTY, BLACK, PAWN, WHITE, EMPTY, WHITE, EMPTY, WHITE, PAWN, WHITE, EMPTY, WHITE, EMPTY, WHITE, EMPTY]
    COL2 = [WHITE, EMPTY, BLACK, PAWN, BLACK, BISHOP, WHITE, PAWN, WHITE, BISHOP, WHITE, EMPTY, BLACK, PAWN, WHITE, EMPTY]
    COL1 = [BLACK, ROOK, WHITE, PAWN, WHITE, EMPTY, BLACK, KNIGHT, WHITE, BISHOP, BLACK, QUEEN, WHITE, PAWN, WHITE, ROOK]
    """
    
    # construct boardstate
    board = COL8 + COL7 + COL6 + COL5 + COL4 + COL3 + COL2 + COL1
    board = ''.join(board)
    return board

def main():
    import os
    filename = "./../simulation/bstate.txt"
    try:
        os.remove(filename)
    except Exception: pass
    
    g = open(filename, 'w')
    g.write(genBoard())
    g.close()

if __name__ == "__main__":
    main()